### ISSUE TITLE
two questions about codes and seed

### ISSUE THREAD

**Issue by zhoucz97** [circle-hit/KBCIN#1]
Question one:
![1671191020334](https://user-images.githubusercontent.com/37372080/208091114-b366bfce-a141-49da-b6e6-9c1ea3cc01c3.png)

As shown in figure, where are these modules, please?

Question two:
Which random seeds did you use, please?  a seed 42 or the seed list [0, 1, 2, 3, 4] ?

**Comment by circle-hit** [comment]
Re Q1:
We submit them now, please check them in ./models

Re Q2:
We use the seed list to perform experiments in five runs.

**Comment by zhoucz97** [comment]
Thanks for your reply. 

However, the models.encoder (UtterEncoder) is still lacking...

**Comment by circle-hit** [comment]
Sorry for the missing. Now it is in ./models~

**Comment by zhoucz97** [comment]
Hi, The `roberta_ptm_{}.pkl` file is not found in your Preprocessed Features from BaiduCloud.
For example:
`FileNotFoundError: [Errno 2] No such file or directory: './data/new_fold1/dailydialog_features_roberta_ptm_train.pkl'`

Could you upload the missing files again?

**Comment by circle-hit** [comment]
Hi, such files "dailydialog_features_roberta_ptm_{}.pkl" can be obtained by running ./get_data.py

**Comment by zhoucz97** [comment]
I saw. Thanks for your reply. 

I am a first year PhD student from Beijing Institue of Technology.  Recently, I am paying attention the RECCON and following your work. Could I add you a WeChat ID?  My WeChat ID is `JoyChou97`

Thanks again.
