### ISSUE TITLE
About csk features

### ISSUE THREAD

**Issue by Tim4Dec** [circle-hit/KBCIN#2]
Hello, could you provide the scripts to extract csk features?  I will be very grateful for your help : )

**Comment by circle-hit** [comment]
Hi, scripts to get csk features are submitted. You can try them and feel free to contact me.

**Comment by Tim4Dec** [comment]
Hi, the uploaded script seems not to be the final version. The data format generated by the script is not the same as the format KBCIN finally used. Could you offer me the final version of the script?  It will help me a lot. Thank you!

**Comment by Tim4Dec** [comment]
> Hi, scripts to get csk features are submitted. You can try them and feel free to contact me.


Hi, the uploaded script seems not to be the final version. The data format generated by the script is not the same as the format KBCIN finally used. Could you offer me the final version of the script? It will help me a lot. Thank you!
