### ISSUE TITLE
The result of KEC model differ from the origin paper

### ISSUE THREAD

**Issue by ruirui3364** [circle-hit/KBCIN#7]
Hello, I notice that the results (neg.f1 pos.f1 macro.f1) of KEC model are 88.85, 66.55, 77.70 in your paper. But in the origin KEC paper (https://arxiv.org/pdf/2205.00759.pdf), the results are 95.74, 66.76, 81.25. I wander why they are different. Thank you.

**Comment by TayeeChang** [comment]
Yes. I also observe this difference. The difference is very large, but in the paper, the author claims that "we reimplement KEC and
methods for ECE in the same setting with us".  I also wanna know the reason.

**Comment by circle-hit** [comment]
> Hello, I notice that the results (neg.f1 pos.f1 macro.f1) of KEC model are 88.85, 66.55, 77.70 in your paper. But in the origin KEC paper (https://arxiv.org/pdf/2205.00759.pdf), the results are 95.74, 66.76, 81.25. I wander why they are different. Thank you.

Hi, thanks for your attention. I mentioned this in the paper that neutral utterances are also involved as targeted utterances in the training set of KEC, leading to more negative non-causal pairs in their processed dataset. And we only focus on the target utterance with non-neural utterances, which is aligned with the motivation of this task and other baselines.

**Comment by ruirui3364** [comment]
Thank you, I got it.
